#!/usr/bin/env tsx

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { generateSCSSConstants } from '../src/constants/uiConstants.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outputPath = path.resolve(__dirname, '../src/ui/styles/abstracts/_constants.scss');

const scssContent = [
  '// Auto-generated from src/constants/uiConstants.ts',
  '// Do not edit this file directly',
  '',
  generateSCSSConstants()
].join('\n');

fs.writeFileSync(outputPath, scssContent);
console.log('Generated SCSS constants file');
